ci/cd: deploy.yml 파일에 zip 파일 생성 스크립트 추가
- deploy.yml 파일에 zip 파일 생성 스크립트 추가함.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -71,7 +71,7 @@ jobs:
           cp Procfile deploy/Procfile
           cp -r .ebextensions deploy/.ebextensions
           cp -r .platform deploy/.platform
-          cd deploy && zip -r deploy.zip .  
+          cd deploy && zip -r deploy.zip .
 
       - name: Beanstalk Deploy
         uses: einaregilsson/beanstalk-deploy@v22
@@ -83,3 +83,12 @@ jobs:
           version_label: github-action-${{steps.current-time.outputs.formattedTime}}
           region: ap-northeast-2
           deployment_package: deploy/deploy.zip
+
+      - name: Check Deployment Status
+        run: |
+          DEPLOY_STATUS=$(aws elasticbeanstalk describe-environments --environment-names ElaBeansBlue-env --query "Environments[0].Status" --output text --region ap-northeast-2)
+          if [ "$DEPLOY_STATUS" != "Ready" ]; then
+            echo "Deployment failed with status: $DEPLOY_STATUS"
+            aws elasticbeanstalk describe-events --environment-name ElaBeansBlue-env --region ap-northeast-2 --max-items 10
+            exit 1
+          fi
